name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
    - name: Create certs
      run: |
        echo "${{ secrets.BUILDBUDDY_ORG_CERT }}">buildbuddy-cert.pem
        echo "${{ secrets.BUILDBUDDY_ORG_KEY }}">buildbuddy-key.pem
    - name: Build
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build --config=ci //...
    - name: Test
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" coverage --config=ci //...
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./bazel-out/k8-fastbuild/testlogs/k8s-dev-scaler_test/coverage.dat,./bazel-out/k8-fastbuild/testlogs/scaler/scaler_test/coverage.dat # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
